modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "itemflicker"
version = "${version}"
displayName = "Item Flicker"
authors = "iMeeTake"
description = '''
Dropped items flicker before disappearing.
'''
#logoFile = ""

[[dependencies.itemflicker]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemflicker]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10]"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemflicker]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "itemflicker.mixins.json"
