modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "itemflicker"
version = "${version}"
displayName = "Item Flicker"
authors = "iMeeTake"
description = '''
Dropped items flicker before disappearing.
'''
#logoFile = ""

[[dependencies.itemflicker]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemflicker]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5]"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemflicker]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "itemflicker.mixins.json"
